In [2]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [3]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [15]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=";")
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT10    100    200  z0019_2.csv 2026-06-03 20:14:02.253142
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-06-03 20:14:02.253142
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-06-03 20:14:02.253142

In [11]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
    	MAKTX VARCHAR,
        WERKS VARCHAR,
    	MAINS VARCHAR,
    	LABST VARCHAR,
    	nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP       
    )
""")

In [18]:
con.execute("INSERT INTO bronze_produtos select * from df")

In [20]:
resultado = con.execute("Select * from bronze_produtos").fetch_df()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-06-03 20:03:45.921036
1  10002   MARTELO  BT50   100   500  z0019_1.csv 2026-06-03 20:03:45.921036
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-06-03 20:03:45.921036
3  10004     SERRA  BT10   100   200  z0019_2.csv 2026-06-03 20:14:02.253142
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-06-03 20:14:02.253142
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-06-03 20:14:02.253142

In [21]:
con.close()