In [1]:
import duckdb

In [3]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [4]:
df = con.execute("select * from produtos").fetch_df()
df.head(30)

      id nm_produto id_categoria  id_fornecedor  vl_preco
0  10001   PARAFUSO         BT10            100     100.0
1  10002    MARTELO         BT50            100     500.0
2  10004      SERRA         BT10            100     200.0
3  10005    MACHADO         BT50            100     100.0
4  10003      PREGO         BT10            100      60.0

In [5]:
df2 = df.drop(columns=['id_categoria', 'id_fornecedor'])
df2.head(10)

      id nm_produto  vl_preco
0  10001   PARAFUSO     100.0
1  10002    MARTELO     500.0
2  10004      SERRA     200.0
3  10005    MACHADO     100.0
4  10003      PREGO      60.0

In [6]:
con.execute("""
    CREATE TABLE IF NOT EXISTS dim_produtos(
        id_produto BIGINT,
        NM_PRODUTO TEXT,
        VL_PRODUTO FLOAT        
    )
""")

In [9]:
con.execute("insert into dim_produtos select * from df2")

In [11]:
df_dim = con.execute("Select * from dim_produtos").fetch_df()
df_dim.head()

   id_produto NM_PRODUTO  VL_PRODUTO
0       10001   PARAFUSO       100.0
1       10002    MARTELO       500.0
2       10004      SERRA       200.0
3       10005    MACHADO       100.0
4       10003      PREGO        60.0

In [12]:
con.close()